import { CharacterData } from './types';
import defaultPortrait from './assets/images/character_portrait_1789770891084.jpg';

export const initialCharacterData: CharacterData = {
  identity: {
    name: 'Elias Iyanu',
    avatarUrl: defaultPortrait,
    height: '1.85m',
    weight: '90kg',
    hair: 'Careca',
    eyes: 'Castanhos escuros',
    skin: 'Negra',
    age: '23',
    ideals: 'Dever, Comunidade, Cultura',
    origin: 'Coração do deserto de Igbalim',
    languages: ['Ma\'isha', 'Igbalim', 'Tantumá'],
  },
  alignment: {
    altruism: 100,
    logic: 100,
    integrity: 0,
  },
  personality: {
    courage: 2,
    conviction: 4,
    serenity: 2,
  },
  attributes: {
    physical: { strength: 3, dexterity: 2, agility: 2, constitution: 3 },
    mental: { intelligence: 2, perception: 3, reasoning: 2, wisdom: 1 },
    social: { empathy: 2, manipulation: 1, expression: 2, resilience: 4 },
  },
  skills: {
    physical: { melee: 3, firearms: 0, archery: 0, throwing: 1, brawl: 2, combat: 2, stealth: 1, alertness: 2 },
    mental: { academics: 1, traps: 0, intuition: 2, investigation: 1, medicine: 0, occultism: 1, security: 0, survival: 3 },
    social: { bargain: 1, taming: 2, etiquette: 1, intimidation: 2, smoothTalk: 0, leadership: 3, riding: 2, seduction: 0 },
  },
  customSkills: {
    treinamentos: [],
    ciencias: [],
    artes: [],
  },
  manaSpent: {
    physical: 0,
    mental: 0,
    social: 0,
  },
  domains: {
    water: 0,
    air: 0,
    anima: 2,
    fire: 1,
    earth: 2,
  },
  naturezaSpent: {
    water: 0,
    air: 0,
    anima: 0,
    fire: 0,
    earth: 0,
  },
  abilities: [
    { id: 'a1', name: 'Bardo de Guerra', description: 'Consegue mesmo em ambientes de batalha, construir rituais', mechanic: 'Foco de bardo + sem debuff instrumento improvisado', cost: '' },
    { id: 'a2', name: 'Golpe Planejado', description: 'strategy do grego strategios', mechanic: 'Batalha+Per dif= perícia+atributo atk+3 sc=bônus acerto', cost: '2 vigor' },
    { id: 'a3', name: 'Potência Vital', description: 'A energia vital fortalece o corpo', mechanic: 'Atributo físico 1.5x em 1 teste', cost: '1 anima' },
    { id: 'a4', name: 'Posição do Pilar', description: 'Firma o toco pra tankar tudo', mechanic: 'usa Cnst+Agi/2 na dif de acerto', cost: '1 vig por golpe' },
    { id: 'a5', name: 'Fortitude Ancestral', description: 'A entidade grandiosa resiste', mechanic: 'soma espírito resistência mágica', cost: '' },
    { id: 'a6', name: 'Reforço Mágico', description: 'A magia do pilar sustenta', mechanic: 'ritual+empatia, dif=complexidade mágica, sc=+estabilidade+du x mana = max bônus cad', cost: '' },
    { id: 'a7', name: 'Nexo Mágico do Pilar', description: 'Toda magia segue o ritmo do pilar', mechanic: 'batuque+empatia, dif=complex mágica, 3 sc=soma limite mágic 3 +1 por ritual', cost: '' }
  ],
  traits: [
    { id: 't1', name: 'Fisicamente Impressionante', type: 'advantage', description: '', value: 1 },
    { id: 't2', name: 'Membro de Organização', type: 'advantage', description: '', value: 1 },
    { id: 't3', name: 'Grandiosidade', type: 'advantage', description: '', value: 4 },
    { id: 't4', name: 'Constituição de Ferro', type: 'advantage', description: '', value: 1 },
    { id: 't5', name: 'Contatos', type: 'advantage', description: '', value: 1 },
    { id: 't6', name: 'Domínio', type: 'advantage', description: '', value: 1 },
    { id: 't7', name: 'Constelação Reencarnada', type: 'advantage', description: '', value: 1 },
    { id: 't8', name: 'Eunuco + Mercenário', type: 'disadvantage', description: '', value: 2 },
    { id: 't9', name: 'Cicatriz de Batalha (Coxa)', type: 'disadvantage', description: '', value: 1 },
    { id: 't10', name: 'Magia Grandiosa', type: 'disadvantage', description: '', value: 1 },
    { id: 't11', name: 'Honesto', type: 'disadvantage', description: '', value: 1 },
    { id: 't12', name: 'Curioso', type: 'disadvantage', description: '', value: 1 },
    { id: 't13', name: 'Segredo (Salvei os Gêmeos)', type: 'disadvantage', description: '', value: 1 },
    { id: 't14', name: 'Coração Mole (Crianças)', type: 'disadvantage', description: '', value: 1 },
    { id: 't15', name: 'Maldição: Megalomania', type: 'disadvantage', description: '', value: 1 }
  ],
  health: {
    head: Array(8).fill('none'),
    torso: Array(20).fill('none'),
    leftArm: Array(12).fill('none'),
    rightArm: Array(12).fill('none'),
    leftLeg: Array(16).fill('none'),
    rightLeg: Array(16).fill('none'),
  },
  inventory: {
    weapons: [
      {
        id: 'w1',
        name: 'Lança de Ferro',
        category: 'weapon',
        equipped: true,
        thrust: { damage: '1d10', type: 'per', ap: 5, precision: 3 },
        swing: { damage: '1d6', type: 'cor', ap: 6, precision: 2 },
        size: 'gg',
        weight: 3000,
        location: 'Em Mãos',
        extras: 'Ponta do cabo de baqueta'
      },
      {
        id: 'w2',
        name: 'Escudo Médio de Ferro',
        category: 'weapon',
        equipped: true,
        thrust: { damage: '1d6', type: 'esm', ap: 4, precision: 0 },
        swing: { damage: '1d8', type: 'esm', ap: 5, precision: 0 },
        size: 'gg',
        weight: 3500,
        location: 'Em Mãos',
        extras: 'Golpe com a borda do escudo'
      },
      {
        id: 'w3',
        name: 'Faca Curta',
        category: 'weapon',
        equipped: false,
        thrust: { damage: '1d4', type: 'cor', ap: 4, precision: 2 },
        swing: { damage: '1d4', type: 'esm', ap: 5, precision: 3 },
        size: 'gg',
        weight: 1200,
        location: 'Cinto',
        extras: ''
      },
      {
        id: 'w4',
        name: 'Baqueta de Tambor',
        category: 'weapon',
        equipped: false,
        thrust: { damage: '1d6', type: 'esm', ap: 5, precision: 2 },
        swing: { damage: '1d6', type: 'esm', ap: 6, precision: 0 },
        size: 'g',
        weight: 120,
        location: 'Mochila',
        extras: 'Instrumento ritualístico e combate contundente'
      },
      {
        id: 'w5',
        name: 'Mambele',
        category: 'weapon',
        equipped: false,
        thrust: { damage: '1d6', type: 'per', ap: 5, precision: 3 },
        swing: { damage: '1d6', type: 'cor', ap: 6, precision: 3 },
        size: 'g',
        weight: 3500,
        location: 'Bainha',
        extras: 'Lâmina curva polivalente'
      },
      {
        id: 'w6',
        name: 'Alabarda da Montanha',
        category: 'weapon',
        equipped: true,
        slot: 'main_hand',
        thrust: { damage: '2d10', type: 'per', ap: 6, precision: 3 },
        swing: { damage: '1d12', type: 'cor', ap: 8, precision: 4 },
        size: 'gg',
        weight: 28000,
        location: 'Em Mãos',
        extras: 'Rompimento do mamute, trespassar'
      }
    ],
    armors: [
      {
        id: 'arm1',
        name: 'Escudo médio de ferro',
        category: 'armor',
        equipped: true,
        slot: 'off_hand',
        slashing: 2,
        bludgeoning: 4,
        piercing: 3,
        coverage: 8,
        resistance: 17,
        durabilityMax: 7,
        durabilityCurrent: 7,
        size: 'ggg',
        weight: 3500,
        location: 'Equipado',
        extras: '+3 ac'
      },
      {
        id: 'arm2',
        name: 'Braçadeiras de Couro',
        category: 'armor',
        equipped: true,
        slot: 'wrist',
        slashing: 0,
        bludgeoning: 0,
        piercing: 0,
        coverage: 7,
        resistance: 15,
        durabilityMax: 8,
        durabilityCurrent: 8,
        size: 'ggg',
        weight: 1000,
        location: 'Equipado',
        extras: ''
      },
      {
        id: 'arm3',
        name: 'Calça de couro',
        category: 'armor',
        equipped: true,
        slot: 'legs',
        slashing: 0,
        bludgeoning: 2,
        piercing: 0,
        coverage: 8,
        resistance: 14,
        durabilityMax: 8,
        durabilityCurrent: 8,
        size: 'gg',
        weight: 1200,
        location: 'Equipado',
        extras: ''
      },
      {
        id: 'arm4',
        name: 'Couraça de Ferro',
        category: 'armor',
        equipped: true,
        slot: 'chest',
        slashing: 2,
        bludgeoning: 4,
        piercing: 2,
        coverage: 8,
        resistance: 20,
        durabilityMax: 10,
        durabilityCurrent: 10,
        size: 'ggg',
        weight: 50000,
        location: 'Equipado',
        extras: ''
      },
      {
        id: 'arm5',
        name: 'Camisa de Couro',
        category: 'armor',
        equipped: true,
        slot: 'chest',
        slashing: 0,
        bludgeoning: 4,
        piercing: 4,
        coverage: 8,
        resistance: 14,
        durabilityMax: 8,
        durabilityCurrent: 8,
        size: 'ggg',
        weight: 3000,
        location: 'Equipado',
        extras: ''
      },
      {
        id: 'arm6',
        name: 'Hauberk',
        category: 'armor',
        equipped: true,
        slot: 'chest',
        slashing: 2,
        bludgeoning: 0,
        piercing: 4,
        coverage: 9,
        resistance: 15,
        durabilityMax: 9,
        durabilityCurrent: 9,
        size: 'gg',
        weight: 12000,
        location: 'Equipado',
        extras: 'Meia coxa cob.7'
      },
      {
        id: 'arm7',
        name: 'Coifa de Malha',
        category: 'armor',
        equipped: true,
        slot: 'head',
        slashing: 4,
        bludgeoning: 0,
        piercing: 3,
        coverage: 8,
        resistance: 15,
        durabilityMax: 9,
        durabilityCurrent: 9,
        size: 'gg',
        weight: 6000,
        location: 'Equipado',
        extras: ''
      },
      {
        id: 'arm8',
        name: 'Bota de Viagem 3*',
        category: 'armor',
        equipped: false,
        slashing: 4,
        bludgeoning: 4,
        piercing: 3,
        coverage: 8,
        resistance: 17,
        durabilityMax: 10,
        durabilityCurrent: 10,
        size: 'ggg',
        weight: 12000,
        location: 'Mochila',
        extras: ''
      },
      {
        id: 'arm9',
        name: 'Manta de Camelo Constelar',
        category: 'armor',
        equipped: false,
        slashing: 0,
        bludgeoning: 4,
        piercing: 0,
        coverage: 9,
        resistance: 13,
        durabilityMax: 12,
        durabilityCurrent: 12,
        size: 'ggg',
        weight: 6000,
        location: 'Mochila',
        extras: 'Conta a história da constelação do camelo'
      },
      {
        id: 'arm10',
        name: 'Bota de Couro',
        category: 'armor',
        equipped: false,
        slashing: 0,
        bludgeoning: 4,
        piercing: 0,
        coverage: 7,
        resistance: 10,
        durabilityMax: 10,
        durabilityCurrent: 10,
        size: 'ggg',
        weight: 3000,
        location: 'Mochila',
        extras: ''
      }
    ],
    projectiles: [
      {
        id: 'p1',
        name: 'Mambele',
        category: 'projectile',
        equipped: true,
        slot: 'off_hand',
        damage: '1d8',
        type: 'cor',
        ap: 5,
        precision: 3,
        quantity: 1,
        size: 'gg',
        weight: 3500,
        location: 'Coldre de Arremesso',
        extras: 'Lâmina aerodinâmica'
      }
    ],
    accessories: [
      {
        id: 'acc1',
        name: 'Couro Trançado dos Iberi',
        category: 'accessory',
        equipped: true,
        slot: 'neck',
        weight: 50,
        location: 'No Pescoço',
        typeAndDesc: 'Amuleto tradicional',
        effect: 'Símbolo de honra e pertencimento aos Iberi'
      },
      {
        id: 'acc2',
        name: 'Tambor pele da montanha',
        category: 'accessory',
        equipped: true,
        slot: 'trinket',
        weight: 650,
        location: 'A Tiracolo',
        typeAndDesc: 'Instrumento ritualístico',
        effect: 'Instrumento de bardo de guerra para rituais e ritmos de combate'
      },
      {
        id: 'acc3',
        name: 'Mochila de Couro Reforçado',
        category: 'accessory',
        equipped: true,
        slot: 'back',
        weight: 650,
        location: 'Costas',
        typeAndDesc: 'Recipiente de carga',
        effect: 'Capacidade de transporte de provisões e itens pesados'
      }
    ],
    generalItems: [
      {
        id: 'gen1',
        name: 'Rações de Viagem (Ração Seca)',
        category: 'general',
        itemType: 'supply',
        quantity: 7,
        weight: 300,
        equipped: false,
        location: 'Mochila',
        description: 'Carne desidratada e frutos secos das montanhas'
      },
      {
        id: 'gen2',
        name: 'Cantil de Couro (Água Fresca)',
        category: 'general',
        itemType: 'supply',
        quantity: 1,
        weight: 1200,
        equipped: true,
        location: 'Cinto',
        description: 'Capacidade para 1,5L de água potável'
      },
      {
        id: 'gen3',
        name: 'Corda de Cânhamo com Gancho (15m)',
        category: 'general',
        itemType: 'tool',
        quantity: 1,
        weight: 2500,
        equipped: false,
        location: 'Mochila',
        description: 'Trançada e reforçada para escalada em encostas'
      },
      {
        id: 'gen4',
        name: 'Tochas de Breu',
        category: 'general',
        itemType: 'supply',
        quantity: 5,
        weight: 400,
        equipped: false,
        location: 'Mochila',
        description: 'Duração aproximada de 1 hora de iluminação cada'
      },
      {
        id: 'gen5',
        name: 'Pederneira e Fita de Pira',
        category: 'general',
        itemType: 'tool',
        quantity: 1,
        weight: 150,
        equipped: true,
        location: 'Bolso Rápido',
        description: 'Iniciador de fogo rápido mesmo sob vento'
      },
      {
        id: 'gen6',
        name: 'Kit de Primeiros Socorros & Ervas',
        category: 'general',
        itemType: 'tool',
        quantity: 3,
        weight: 500,
        equipped: false,
        location: 'Mochila',
        description: 'Bandagens de linho, unguento de arnica e ervas estancadoras'
      },
      {
        id: 'gen7',
        name: 'Poção de Vitalidade Menor',
        category: 'general',
        itemType: 'consumable',
        quantity: 2,
        weight: 250,
        equipped: true,
        location: 'Coldre do Cinto',
        description: 'Restaura 1d8+2 PV ao ser ingerida como ação rápida'
      },
      {
        id: 'gen8',
        name: 'Saco de Dormir e Manta de Lã',
        category: 'general',
        itemType: 'supply',
        quantity: 1,
        weight: 2200,
        equipped: false,
        location: 'Mochila',
        description: 'Isolamento térmico para noites frias de acampamento'
      }
    ],
    currency: {
      gold: 49,
      silver: 0,
      copper: 92,
      gems: '',
      history: [
        { id: 'tx-1', type: 'income', amount: 15, coin: 'gold', reason: 'Recompensa do Contrato', timestamp: Date.now() - 14400000 },
        { id: 'tx-2', type: 'expense', amount: 8, coin: 'silver', reason: 'Estalagem & Provisões', timestamp: Date.now() - 7200000 },
        { id: 'tx-3', type: 'income', amount: 30, coin: 'copper', reason: 'Venda de espólio', timestamp: Date.now() - 3600000 }
      ]
    }
  },
  flowAndPatron: {
    fluxo: {
      level: 3,
      hp: 10,
      name: 'Fluxo Cósmico',
      notes: 'Corrente contínua de éter que atravessa o arcano.'
    },
    patrono: {
      level: 4,
      hp: 10,
      name: 'Guardião do Pilar Igbalim',
      notes: 'Entidade solar ancestral que concedeu a bênção de sangue.'
    }
  }
};
